### ISSUE TITLE
About BlendShape

### ISSUE THREAD

**Issue by www516717402** [KangweiiLiu/Awesome_Audio-driven_Talking-Face-Generation#1]
Have you find paper with regression BlendShape?

**Comment by KangweiiLiu** [comment]
Thanks for questioning.
For the pure regression BlendShape model, you can check the papers below:
Audio-driven Talking Face Video Generation with Learning-based Personalized Head Pose  
FACIAL: Synthesizing Dynamic Talking Face with Implicit Attribute Learning
